runtime: python37

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: ''
  CLOUD_SQL_DATABASE_NAME: api
  CLOUD_SQL_CONNECTION_NAME: julian-316314:us-central1:api-flask
